service: sls-git-template

disabledDeprecations:
  - LAMBDA_HASHING_VERSION_V2
  - AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
plugins:
  - serverless-deployment-bucket
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: ${opt:runtime, 'nodejs12.x'}
  stage: ${self:custom.environment}
  region: ${self:custom.region}
  deploymentBucket:
    name: pbx-sls-${self:custom.environment}-assets
  environment:
    NODE_CONFIG_ENV: ${self:custom.environment}

package:
  individually: true
  exclude:
    - .cache/**
    - .github/**
    - docs/**
    - serverless/**
    - src/**
    - package.json
    - README.md

custom:
  account: ${self:custom.envSpecific.${self:custom.environment}.account, "855439869752"}
  certId: ${self:custom.envSpecific.${self:custom.environment}.certId, "02cfa665-61ff-4477-82f2-2d9c719d0c42"}
  certEnv: ${self:custom.envSpecific.${self:custom.environment}.certEnv, "test"}
  environment: ${opt:stage, "development"}
  region: ${opt:region, "eu-west-1"}
  stackName: ${self:service}-${self:custom.envSpecific.${self:custom.environment}.serviceName}
  vpcStackName: jenkins-ecom-example-${self:custom.envSpecific.${self:custom.environment}.nodeEnv}

  serverless-offline:
    httpPort: 3010
    noPrependStageInUrl: true
    useChildProcesses: true

  prune:
    automatic: true
    includeLayers: true
    number: ${self:custom.envSpecific.${self:custom.environment}.pruneRetention}

  envSpecific:
    local: ${file(serverless/env/local.yml)}
    feature: ${file(serverless/env/feature.yml)}
    development: ${file(serverless/env/development.yml)}
    staging: ${file(serverless/env/staging.yml)}
    production: ${file(serverless/env/production.yml)}

functions:
  exampleFunction: ${file(./serverless/functions/example.yml)}

resources:
  Resources:
    ExampleExecutionRole: ${file(serverless/roles/example-execution-role.yml)}
    ExampleDomainName: ${file(serverless/domains/example-domain-name.yml)}
    ExampleBasePathMapping: ${file(serverless/domains/example-base-path-mapping.yml)}
